// Mocks generated by Mockito 5.4.6 from annotations
// in tourlicity_app/test/presentation/blocs/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tourlicity_app/core/network/api_result.dart' as _i4;
import 'package:tourlicity_app/domain/entities/auth_user.dart' as _i7;
import 'package:tourlicity_app/domain/entities/google_sign_in_result.dart'
    as _i5;
import 'package:tourlicity_app/domain/repositories/auth_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.GoogleSignInResult>> signInWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.GoogleSignInResult>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.GoogleSignInResult>>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.GoogleSignInResult>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.AuthUser>> authenticateWithGoogle({
    required String? idToken,
    required String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateWithGoogle,
          [],
          {
            #idToken: idToken,
            #accessToken: accessToken,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i7.AuthUser>>.value(
            _i6.dummyValue<_i4.ApiResult<_i7.AuthUser>>(
          this,
          Invocation.method(
            #authenticateWithGoogle,
            [],
            {
              #idToken: idToken,
              #accessToken: accessToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.AuthUser>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.AuthUser?>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i7.AuthUser?>>.value(
            _i6.dummyValue<_i4.ApiResult<_i7.AuthUser?>>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.AuthUser?>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.AuthUser>> refreshTokens() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshTokens,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i7.AuthUser>>.value(
            _i6.dummyValue<_i4.ApiResult<_i7.AuthUser>>(
          this,
          Invocation.method(
            #refreshTokens,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.AuthUser>>);

  @override
  _i3.Future<_i4.ApiResult<void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i6.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
