# Build configuration for different environments
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      retrofit_generator:
        options:
          generate_to_string: true