// Mocks generated by Mockito 5.4.6 from annotations
// in tourlicity_app/test/core/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tourlicity_app/core/network/api_client.dart' as _i2;
import 'package:tourlicity_app/core/network/api_result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> delete<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> uploadFile<T>(
    String? path,
    String? filePath, {
    String? fieldName = 'file',
    Map<String, String>? fields,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            path,
            filePath,
          ],
          {
            #fieldName: fieldName,
            #fields: fields,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #uploadFile,
            [
              path,
              filePath,
            ],
            {
              #fieldName: fieldName,
              #fields: fields,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);
}
