// Mocks generated by Mockito 5.4.6 from annotations
// in tourlicity_app/test/presentation/blocs/custom_tour/custom_tour_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tourlicity_app/core/network/api_result.dart' as _i4;
import 'package:tourlicity_app/domain/entities/custom_tour.dart' as _i5;
import 'package:tourlicity_app/domain/repositories/custom_tour_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CustomTourRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomTourRepository extends _i1.Mock
    implements _i2.CustomTourRepository {
  MockCustomTourRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>> getCustomTours({
    String? providerId,
    _i5.TourStatus? status,
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomTours,
          [],
          {
            #providerId: providerId,
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.CustomTour>>>(
          this,
          Invocation.method(
            #getCustomTours,
            [],
            {
              #providerId: providerId,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> getCustomTourById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomTourById,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #getCustomTourById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> getCustomTourByJoinCode(
          String? joinCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomTourByJoinCode,
          [joinCode],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #getCustomTourByJoinCode,
            [joinCode],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> createCustomTour(
          _i5.CustomTour? customTour) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomTour,
          [customTour],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #createCustomTour,
            [customTour],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> updateCustomTour(
          _i5.CustomTour? customTour) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomTour,
          [customTour],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #updateCustomTour,
            [customTour],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<void>> deleteCustomTour(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomTour,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i6.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #deleteCustomTour,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> updateTourStatus(
    String? id,
    _i5.TourStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTourStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #updateTourStatus,
            [
              id,
              status,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> publishTour(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishTour,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #publishTour,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> cancelTour(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelTour,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #cancelTour,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> startTour(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTour,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #startTour,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> completeTour(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTour,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #completeTour,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> updateTouristCount(
    String? id,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTouristCount,
          [
            id,
            count,
          ],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #updateTouristCount,
            [
              id,
              count,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.CustomTour>> generateNewJoinCode(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateNewJoinCode,
          [id],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.CustomTour>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.CustomTour>>(
          this,
          Invocation.method(
            #generateNewJoinCode,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CustomTour>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>> searchTours({
    String? query,
    List<String>? tags,
    DateTime? startDateFrom,
    DateTime? startDateTo,
    double? minPrice,
    double? maxPrice,
    _i5.TourStatus? status,
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTours,
          [],
          {
            #query: query,
            #tags: tags,
            #startDateFrom: startDateFrom,
            #startDateTo: startDateTo,
            #minPrice: minPrice,
            #maxPrice: maxPrice,
            #status: status,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.CustomTour>>>(
          this,
          Invocation.method(
            #searchTours,
            [],
            {
              #query: query,
              #tags: tags,
              #startDateFrom: startDateFrom,
              #startDateTo: startDateTo,
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #status: status,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.CustomTour>>>);
}
