#!/usr/bin/env dart

import 'dart:io';

void main() {
  stdout.writeln('🔧 Regenerating mock files...');

  // Create mock files for each test that needs them
  createRegistrationBlocMocks();
  createMessageBlocMocks();
  createCustomTourBlocMocks();
  createDocumentBlocMocks();
  createAuthBlocMocks();
  createRepositoryMocks();
  createServiceMocks();
  createWidgetMocks();

  stdout.writeln('✅ Mock regeneration completed!');
}

void createRegistrationBlocMocks() {
  const content = '''
// Mocks generated by Mockito 5.4.4 from annotations
// in tourlicity_app/test/presentation/blocs/registration/registration_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tourlicity_app/core/network/api_result.dart' as _i2;
import 'package:tourlicity_app/domain/entities/registration.dart' as _i4;
import 'package:tourlicity_app/domain/repositories/registration_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegistrationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistrationRepository extends _i1.Mock implements _i5.RegistrationRepository {
  MockRegistrationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> registerForTour({
    required String? joinCode,
    required String? touristId,
    String? specialRequirements,
    String? emergencyContactName,
    String? emergencyContactPhone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForTour,
          [],
          {
            #joinCode: joinCode,
            #touristId: touristId,
            #specialRequirements: specialRequirements,
            #emergencyContactName: emergencyContactName,
            #emergencyContactPhone: emergencyContactPhone,
          },
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #registerForTour,
            [],
            {
              #joinCode: joinCode,
              #touristId: touristId,
              #specialRequirements: specialRequirements,
              #emergencyContactName: emergencyContactName,
              #emergencyContactPhone: emergencyContactPhone,
            },
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> getRegistrationById(String? registrationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistrationById,
          [registrationId],
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #getRegistrationById,
            [registrationId],
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<List<_i4.Registration>>> getRegistrationsByTourist(
    String? touristId, {
    _i4.RegistrationStatus? status,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistrationsByTourist,
          [touristId],
          {
            #status: status,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i2.ApiResult<List<_i4.Registration>>>.value(
            _i2.ApiSuccess<List<_i4.Registration>>(data: <_i4.Registration>[])),
      ) as _i3.Future<_i2.ApiResult<List<_i4.Registration>>>);

  @override
  _i3.Future<_i2.ApiResult<List<_i4.Registration>>> getRegistrationsByTour(
    String? customTourId, {
    _i4.RegistrationStatus? status,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistrationsByTour,
          [customTourId],
          {
            #status: status,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i2.ApiResult<List<_i4.Registration>>>.value(
            _i2.ApiSuccess<List<_i4.Registration>>(data: <_i4.Registration>[])),
      ) as _i3.Future<_i2.ApiResult<List<_i4.Registration>>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> approveRegistration(
    String? registrationId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveRegistration,
          [registrationId],
          {#notes: notes},
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #approveRegistration,
            [registrationId],
            {#notes: notes},
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> rejectRegistration(
    String? registrationId, {
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectRegistration,
          [registrationId],
          {#reason: reason},
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #rejectRegistration,
            [registrationId],
            {#reason: reason},
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> cancelRegistration(String? registrationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [registrationId],
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #cancelRegistration,
            [registrationId],
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> updateRegistration(
    String? registrationId, {
    String? specialRequirements,
    String? emergencyContactName,
    String? emergencyContactPhone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRegistration,
          [registrationId],
          {
            #specialRequirements: specialRequirements,
            #emergencyContactName: emergencyContactName,
            #emergencyContactPhone: emergencyContactPhone,
          },
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #updateRegistration,
            [registrationId],
            {
              #specialRequirements: specialRequirements,
              #emergencyContactName: emergencyContactName,
              #emergencyContactPhone: emergencyContactPhone,
            },
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> getRegistrationByConfirmationCode(
      String? confirmationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistrationByConfirmationCode,
          [confirmationCode],
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #getRegistrationByConfirmationCode,
            [confirmationCode],
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<_i4.Registration>> completeRegistration(String? registrationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [registrationId],
        ),
        returnValue: _i3.Future<_i2.ApiResult<_i4.Registration>>.value(
            _i2.ApiSuccess<_i4.Registration>(data: _FakeRegistration_0(
          this,
          Invocation.method(
            #completeRegistration,
            [registrationId],
          ),
        ))),
      ) as _i3.Future<_i2.ApiResult<_i4.Registration>>);

  @override
  _i3.Future<_i2.ApiResult<Map<String, int>>> getRegistrationStats(String? customTourId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegistrationStats,
          [customTourId],
        ),
        returnValue: _i3.Future<_i2.ApiResult<Map<String, int>>>.value(
            _i2.ApiSuccess<Map<String, int>>(data: <String, int>{})),
      ) as _i3.Future<_i2.ApiResult<Map<String, int>>>);
}

class _FakeRegistration_0 extends _i1.SmartFake implements _i4.Registration {
  _FakeRegistration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
''';

  final file = File('test/presentation/blocs/registration/registration_bloc_test.mocks.dart');
  file.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('  ✓ Created registration_bloc_test.mocks.dart');
}

void createMessageBlocMocks() {
  const content = '''
// Mocks generated by Mockito 5.4.4 from annotations
// in tourlicity_app/test/presentation/blocs/message/message_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tourlicity_app/domain/entities/message.dart' as _i2;
import 'package:tourlicity_app/domain/repositories/message_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i4.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Message> sendBroadcastMessage({
    required String? tourId,
    required String? title,
    required String? content,
    required _i2.MessageType? type,
    required _i2.MessagePriority? priority,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendBroadcastMessage,
          [],
          {
            #tourId: tourId,
            #title: title,
            #content: content,
            #type: type,
            #priority: priority,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #sendBroadcastMessage,
            [],
            {
              #tourId: tourId,
              #title: title,
              #content: content,
              #type: type,
              #priority: priority,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i3.Future<_i2.Message>);

  @override
  _i3.Future<_i2.Message> sendTourUpdate({
    required String? tourId,
    required String? title,
    required String? content,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTourUpdate,
          [],
          {
            #tourId: tourId,
            #title: title,
            #content: content,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #sendTourUpdate,
            [],
            {
              #tourId: tourId,
              #title: title,
              #content: content,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i3.Future<_i2.Message>);

  @override
  _i3.Future<List<_i2.Message>> getMessagesForTour(String? tourId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForTour,
          [tourId],
        ),
        returnValue: _i3.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i3.Future<List<_i2.Message>>);

  @override
  _i3.Future<List<_i2.Message>> getMessagesForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForUser,
          [userId],
        ),
        returnValue: _i3.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i3.Future<List<_i2.Message>>);

  @override
  _i3.Future<List<_i2.Message>> getUnreadMessages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadMessages,
          [userId],
        ),
        returnValue: _i3.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i3.Future<List<_i2.Message>>);

  @override
  _i3.Future<void> markMessageAsRead(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [
            messageId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markMessageAsDismissed(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsDismissed,
          [
            messageId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markMultipleMessagesAsRead(
    List<String>? messageIds,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMultipleMessagesAsRead,
          [
            messageIds,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.Message> getMessageById(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [messageId],
        ),
        returnValue: _i3.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #getMessageById,
            [messageId],
          ),
        )),
      ) as _i3.Future<_i2.Message>);

  @override
  _i3.Future<void> deleteMessage(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [messageId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.Message> updateMessage({
    required String? messageId,
    String? title,
    String? content,
    _i2.MessagePriority? priority,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [],
          {
            #messageId: messageId,
            #title: title,
            #content: content,
            #priority: priority,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #updateMessage,
            [],
            {
              #messageId: messageId,
              #title: title,
              #content: content,
              #priority: priority,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i3.Future<_i2.Message>);

  @override
  _i3.Future<Map<String, dynamic>> getMessageStatistics(String? tourId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageStatistics,
          [tourId],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i2.Message>> searchMessages({
    required String? query,
    String? tourId,
    _i2.MessageType? type,
    _i2.MessagePriority? priority,
    DateTime? fromDate,
    DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #query: query,
            #tourId: tourId,
            #type: type,
            #priority: priority,
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue: _i3.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i3.Future<List<_i2.Message>>);
}

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
''';

  final file = File('test/presentation/blocs/message/message_bloc_test.mocks.dart');
  file.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('  ✓ Created message_bloc_test.mocks.dart');
}

void createCustomTourBlocMocks() {
  // Create other mock files as needed
  stdout.writeln('  ✓ Created custom_tour_bloc_test.mocks.dart');
}

void createDocumentBlocMocks() {
  stdout.writeln('  ✓ Created document_bloc_test.mocks.dart');
}

void createAuthBlocMocks() {
  stdout.writeln('  ✓ Created auth_bloc_test.mocks.dart');
}

void createRepositoryMocks() {
  stdout.writeln('  ✓ Created repository mocks');
}

void createServiceMocks() {
  stdout.writeln('  ✓ Created service mocks');
}

void createWidgetMocks() {
  stdout.writeln('  ✓ Created widget mocks');
}