// Mocks generated by Mockito 5.4.6 from annotations
// in tourlicity_app/test/presentation/blocs/document/document_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tourlicity_app/core/network/api_result.dart' as _i4;
import 'package:tourlicity_app/domain/entities/document.dart' as _i5;
import 'package:tourlicity_app/domain/repositories/document_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i2.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.Document>> uploadDocument({
    required String? filePath,
    required String? userId,
    String? tourId,
    required _i5.DocumentType? type,
    String? description,
    DateTime? expiryDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDocument,
          [],
          {
            #filePath: filePath,
            #userId: userId,
            #tourId: tourId,
            #type: type,
            #description: description,
            #expiryDate: expiryDate,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.Document>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.Document>>(
          this,
          Invocation.method(
            #uploadDocument,
            [],
            {
              #filePath: filePath,
              #userId: userId,
              #tourId: tourId,
              #type: type,
              #description: description,
              #expiryDate: expiryDate,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.Document>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.Document>> getDocumentById(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentById,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.Document>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.Document>>(
          this,
          Invocation.method(
            #getDocumentById,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.Document>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> getDocumentsByUser({
    required String? userId,
    _i5.DocumentType? type,
    _i5.DocumentStatus? status,
    String? tourId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByUser,
          [],
          {
            #userId: userId,
            #type: type,
            #status: status,
            #tourId: tourId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #getDocumentsByUser,
            [],
            {
              #userId: userId,
              #type: type,
              #status: status,
              #tourId: tourId,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> getDocumentsByTour({
    required String? tourId,
    _i5.DocumentType? type,
    _i5.DocumentStatus? status,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTour,
          [],
          {
            #tourId: tourId,
            #type: type,
            #status: status,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #getDocumentsByTour,
            [],
            {
              #tourId: tourId,
              #type: type,
              #status: status,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> getDocumentsForReview({
    String? providerId,
    String? tourId,
    _i5.DocumentType? type,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsForReview,
          [],
          {
            #providerId: providerId,
            #tourId: tourId,
            #type: type,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #getDocumentsForReview,
            [],
            {
              #providerId: providerId,
              #tourId: tourId,
              #type: type,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<String>> getDownloadUrl(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadUrl,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.ApiResult<String>>.value(
            _i6.dummyValue<_i4.ApiResult<String>>(
          this,
          Invocation.method(
            #getDownloadUrl,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<String>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.Document>> approveDocument({
    required String? documentId,
    String? notes,
    required String? reviewedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveDocument,
          [],
          {
            #documentId: documentId,
            #notes: notes,
            #reviewedBy: reviewedBy,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.Document>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.Document>>(
          this,
          Invocation.method(
            #approveDocument,
            [],
            {
              #documentId: documentId,
              #notes: notes,
              #reviewedBy: reviewedBy,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.Document>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.Document>> rejectDocument({
    required String? documentId,
    required String? reason,
    required String? reviewedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectDocument,
          [],
          {
            #documentId: documentId,
            #reason: reason,
            #reviewedBy: reviewedBy,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.Document>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.Document>>(
          this,
          Invocation.method(
            #rejectDocument,
            [],
            {
              #documentId: documentId,
              #reason: reason,
              #reviewedBy: reviewedBy,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.Document>>);

  @override
  _i3.Future<_i4.ApiResult<void>> deleteDocument(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i6.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #deleteDocument,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.Document>> updateDocument({
    required String? documentId,
    String? description,
    DateTime? expiryDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [],
          {
            #documentId: documentId,
            #description: description,
            #expiryDate: expiryDate,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.Document>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.Document>>(
          this,
          Invocation.method(
            #updateDocument,
            [],
            {
              #documentId: documentId,
              #description: description,
              #expiryDate: expiryDate,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.Document>>);

  @override
  _i3.Future<_i4.ApiResult<Map<String, int>>> getDocumentStats({
    String? userId,
    String? tourId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentStats,
          [],
          {
            #userId: userId,
            #tourId: tourId,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<Map<String, int>>>.value(
            _i6.dummyValue<_i4.ApiResult<Map<String, int>>>(
          this,
          Invocation.method(
            #getDocumentStats,
            [],
            {
              #userId: userId,
              #tourId: tourId,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<Map<String, int>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> searchDocuments({
    String? query,
    String? userId,
    String? tourId,
    _i5.DocumentType? type,
    _i5.DocumentStatus? status,
    DateTime? uploadedAfter,
    DateTime? uploadedBefore,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [],
          {
            #query: query,
            #userId: userId,
            #tourId: tourId,
            #type: type,
            #status: status,
            #uploadedAfter: uploadedAfter,
            #uploadedBefore: uploadedBefore,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #searchDocuments,
            [],
            {
              #query: query,
              #userId: userId,
              #tourId: tourId,
              #type: type,
              #status: status,
              #uploadedAfter: uploadedAfter,
              #uploadedBefore: uploadedBefore,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> getExpiringDocuments({
    String? userId,
    String? tourId,
    int? daysAhead = 30,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpiringDocuments,
          [],
          {
            #userId: userId,
            #tourId: tourId,
            #daysAhead: daysAhead,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #getExpiringDocuments,
            [],
            {
              #userId: userId,
              #tourId: tourId,
              #daysAhead: daysAhead,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> bulkApproveDocuments({
    required List<String>? documentIds,
    String? notes,
    required String? reviewedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkApproveDocuments,
          [],
          {
            #documentIds: documentIds,
            #notes: notes,
            #reviewedBy: reviewedBy,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #bulkApproveDocuments,
            [],
            {
              #documentIds: documentIds,
              #notes: notes,
              #reviewedBy: reviewedBy,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i5.Document>>> bulkRejectDocuments({
    required List<String>? documentIds,
    required String? reason,
    required String? reviewedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkRejectDocuments,
          [],
          {
            #documentIds: documentIds,
            #reason: reason,
            #reviewedBy: reviewedBy,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.Document>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.Document>>>(
          this,
          Invocation.method(
            #bulkRejectDocuments,
            [],
            {
              #documentIds: documentIds,
              #reason: reason,
              #reviewedBy: reviewedBy,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.Document>>>);
}
